CREATE TABLE IF NOT EXISTS Products (
	productId   integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    productName varchar(200) NOT NULL,
    description text,
	categoryId integer
);

CREATE TABLE IF NOT EXISTS Categories (
	categoryId  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    categoryName varchar(200) NOT NULL,
    description text
);

INSERT INTO Categories(categoryName, description)
VALUES('Electronics', 'Day la do dien tu');
INSERT INTO Categories(categoryName, description)
VALUES('Foods', 'Do an , food');
INSERT INTO Categories(categoryName, description)
VALUES('Banh keo', 'Banh keo, do ngot');
SELECT * FROM Categories;

